chore(deps): update spring boot to v3.1.2 (#8470)
[![Mend Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [org.springframework.boot:spring-boot-maven-plugin](https://spring.io/projects/spring-boot) ([source](https://togithub.com/spring-projects/spring-boot)) | `3.1.1` -> `3.1.2` | [![age](https://developer.mend.io/api/mc/badges/age/maven/org.springframework.boot:spring-boot-maven-plugin/3.1.2?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/org.springframework.boot:spring-boot-maven-plugin/3.1.2?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/org.springframework.boot:spring-boot-maven-plugin/3.1.1/3.1.2?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/org.springframework.boot:spring-boot-maven-plugin/3.1.1/3.1.2?slim=true)](https://docs.renovatebot.com/merge-confidence/) |
| [org.springframework.boot:spring-boot-dependencies](https://spring.io/projects/spring-boot) ([source](https://togithub.com/spring-projects/spring-boot)) | `3.1.1` -> `3.1.2` | [![age](https://developer.mend.io/api/mc/badges/age/maven/org.springframework.boot:spring-boot-dependencies/3.1.2?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/org.springframework.boot:spring-boot-dependencies/3.1.2?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/org.springframework.boot:spring-boot-dependencies/3.1.1/3.1.2?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/org.springframework.boot:spring-boot-dependencies/3.1.1/3.1.2?slim=true)](https://docs.renovatebot.com/merge-confidence/) |

---

### ⚠ Dependency Lookup Warnings ⚠

Warnings were logged while processing this repo. Please check the Dependency Dashboard for more information.

---

### Release Notes

<details>
<summary>spring-projects/spring-boot (org.springframework.boot:spring-boot-maven-plugin)</summary>

### [`v3.1.2`](https://togithub.com/spring-projects/spring-boot/releases/tag/v3.1.2)

[Compare Source](https://togithub.com/spring-projects/spring-boot/compare/v3.1.1...v3.1.2)

#### :lady_beetle: Bug Fixes

-   Native reflection hints missing for nested properties declared in a superclass [#&#8203;36448](https://togithub.com/spring-projects/spring-boot/issues/36448)
-   Connecting to Mongo fails with an UnknownHostException when spring.data.mongodb.additional-hosts is configured [#&#8203;36441](https://togithub.com/spring-projects/spring-boot/issues/36441)
-   Auto-configured ExemplarSampler bean only backs off when a DefaultExemplarSampler is defined [#&#8203;36429](https://togithub.com/spring-projects/spring-boot/issues/36429)
-   OTel Span is missing required attributes [#&#8203;36423](https://togithub.com/spring-projects/spring-boot/issues/36423)
-   Auto-configured JacksonJsonpMapper is conditional on an ObjectMapper bean but does not use such a bean [#&#8203;36409](https://togithub.com/spring-projects/spring-boot/issues/36409)
-   Application fails to start when `@Import`ing a `@ConfigurationProperties` class that is eligible for constructor binding [#&#8203;36359](https://togithub.com/spring-projects/spring-boot/issues/36359)
-   Only one health group can be exposed using management.endpoint.health.group.xxx.additional-path=server:/newpath when using Jersey [#&#8203;36276](https://togithub.com/spring-projects/spring-boot/issues/36276)
-   Mongo auto-configuration fails when username or password properties contains a colon (`:`) or at-sign (`@`) [#&#8203;36261](https://togithub.com/spring-projects/spring-boot/issues/36261)
-   MockitoPostProcessor doesn't check FactoryBean.OBJECT_TYPE_ATTRIBUTE correctly [#&#8203;36230](https://togithub.com/spring-projects/spring-boot/issues/36230)
-   ImportsContextCustomizer does not support AliasFor [#&#8203;36209](https://togithub.com/spring-projects/spring-boot/issues/36209)
-   Saml2RelyingPartyRegistrationConfiguration can choose the wrong RelyingPartyRegistration.Builder when using a metadata file with multiple providers [#&#8203;36163](https://togithub.com/spring-projects/spring-boot/issues/36163)
-   ConfigurationPropertiesReportEndpoint does not display primitive wrapper types [#&#8203;36160](https://togithub.com/spring-projects/spring-boot/issues/36160)
-   ConfigurationPropertyName#equals is not symmetric when element has trailing dashes [#&#8203;36145](https://togithub.com/spring-projects/spring-boot/issues/36145)
-   ScheduledTasksEndpoint throws NPE if PeriodicTrigger is used with custom SchedulingConfigurer [#&#8203;36129](https://togithub.com/spring-projects/spring-boot/issues/36129)
-   Java system properties can not be applied to RestTemplate HttpClient connection in some cases [#&#8203;36123](https://togithub.com/spring-projects/spring-boot/issues/36123)
-   Excluding auto-configuration class that relates to a TemplateAvailabilityProvider causes property binding to fail for native images [#&#8203;36121](https://togithub.com/spring-projects/spring-boot/issues/36121)
-   When using Flyway 9.20.0, auto-configuration fails with a NoSuchMethodError due to the removal of Oracle-related methods from FluentConfiguration [#&#8203;36099](https://togithub.com/spring-projects/spring-boot/issues/36099)
-   Dependency management for Selenium 4.8.x is incorrect [#&#8203;36077](https://togithub.com/spring-projects/spring-boot/pull/36077)
-   Slice test annotations do not include SslAutoConfiguration [#&#8203;36038](https://togithub.com/spring-projects/spring-boot/pull/36038)
-   Methods in KafkaConnectionDetails are named inconsistently [#&#8203;35733](https://togithub.com/spring-projects/spring-boot/pull/35733)

#### :notebook_with_decorative_cover: Documentation

-   Documented Servlet container system requirements are out of date [#&#8203;36355](https://togithub.com/spring-projects/spring-boot/issues/36355)
-   Update the javadoc of ClientHttpRequestFactories to describe the ClientHttpRequestFactory implementations that it supports [#&#8203;36268](https://togithub.com/spring-projects/spring-boot/issues/36268)
-   Polish formatting in "Running Spring Batch Jobs on Startup" [#&#8203;36233](https://togithub.com/spring-projects/spring-boot/issues/36233)
-   Improve Kubernetes liveness and readiness probes customization documentation [#&#8203;36219](https://togithub.com/spring-projects/spring-boot/issues/36219)
-   Document auto-configuration of underlying HTTP client when using WebClient or RestTemplate [#&#8203;36215](https://togithub.com/spring-projects/spring-boot/issues/36215)
-   Polish Kafka Properties Docs [#&#8203;36142](https://togithub.com/spring-projects/spring-boot/issues/36142)
-   Fix typo in the Using R2DBC section of the reference documentation [#&#8203;36139](https://togithub.com/spring-projects/spring-boot/issues/36139)
-   Document observability auto-configuration for HTTP clients [#&#8203;36131](https://togithub.com/spring-projects/spring-boot/issues/36131)
-   Improve documentation for baggage propagation into MDC [#&#8203;36112](https://togithub.com/spring-projects/spring-boot/issues/36112)
-   Javadoc of RestTemplateBuilder.requestFactory(Function) links to deprecated ClientHttpRequestFactorySupplier [#&#8203;36097](https://togithub.com/spring-projects/spring-boot/issues/36097)
-   Javadoc of ConstructorBound and ConfigurationProperties links to deprecated ConstructorBinding annotation [#&#8203;36095](https://togithub.com/spring-projects/spring-boot/issues/36095)
-   Add Javadoc since to ImageReference.inTaglessForm() [#&#8203;36054](https://togithub.com/spring-projects/spring-boot/issues/36054)
-   Fix typo in docker compose service connections note [#&#8203;36016](https://togithub.com/spring-projects/spring-boot/pull/36016)

#### :hammer: Dependency Upgrades

-   Upgrade to ActiveMQ 5.18.2 [#&#8203;36332](https://togithub.com/spring-projects/spring-boot/issues/36332)
-   Upgrade to Dependency Management Plugin 1.1.2 [#&#8203;36435](https://togithub.com/spring-projects/spring-boot/issues/36435)
-   Upgrade to Groovy 4.0.13 [#&#8203;36333](https://togithub.com/spring-projects/spring-boot/issues/36333)
-   Upgrade to Hibernate 6.2.6.Final [#&#8203;36334](https://togithub.com/spring-projects/spring-boot/issues/36334)
-   Upgrade to Hibernate Validator 8.0.1.Final [#&#8203;36335](https://togithub.com/spring-projects/spring-boot/issues/36335)
-   Upgrade to Infinispan 14.0.12.Final [#&#8203;36336](https://togithub.com/spring-projects/spring-boot/issues/36336)
-   Upgrade to Jakarta WebSocket 2.1.1 [#&#8203;36337](https://togithub.com/spring-projects/spring-boot/issues/36337)
-   Upgrade to Janino 3.1.10 [#&#8203;36338](https://togithub.com/spring-projects/spring-boot/issues/36338)
-   Upgrade to JBoss Logging 3.5.3.Final [#&#8203;36339](https://togithub.com/spring-projects/spring-boot/issues/36339)
-   Upgrade to jOOQ 3.18.5 [#&#8203;36340](https://togithub.com/spring-projects/spring-boot/issues/36340)
-   Upgrade to Lettuce 6.2.5.RELEASE [#&#8203;36436](https://togithub.com/spring-projects/spring-boot/issues/36436)
-   Upgrade to Micrometer 1.11.2 [#&#8203;36183](https://togithub.com/spring-projects/spring-boot/issues/36183)
-   Upgrade to Micrometer Tracing 1.1.3 [#&#8203;36296](https://togithub.com/spring-projects/spring-boot/issues/36296)
-   Upgrade to R2DBC MSSQL 1.0.2.RELEASE [#&#8203;36467](https://togithub.com/spring-projects/spring-boot/issues/36467)
-   Upgrade to R2DBC Postgresql 1.0.2.RELEASE [#&#8203;36469](https://togithub.com/spring-projects/spring-boot/issues/36469)
-   Upgrade to Rabbit AMQP Client 5.17.1 [#&#8203;36341](https://togithub.com/spring-projects/spring-boot/issues/36341)
-   Upgrade to Reactor Bom 2022.0.9 [#&#8203;36297](https://togithub.com/spring-projects/spring-boot/issues/36297)
-   Upgrade to Spring AMQP 3.0.6 [#&#8203;36403](https://togithub.com/spring-projects/spring-boot/issues/36403)
-   Upgrade to Spring Data Bom 2023.0.2 [#&#8203;36184](https://togithub.com/spring-projects/spring-boot/issues/36184)
-   Upgrade to Spring Framework 6.0.11 [#&#8203;36185](https://togithub.com/spring-projects/spring-boot/issues/36185)
-   Upgrade to Spring GraphQL 1.2.2 [#&#8203;36186](https://togithub.com/spring-projects/spring-boot/issues/36186)
-   Upgrade to Spring HATEOAS 2.1.2 [#&#8203;36454](https://togithub.com/spring-projects/spring-boot/issues/36454)
-   Upgrade to Spring Integration 6.1.2 [#&#8203;36404](https://togithub.com/spring-projects/spring-boot/issues/36404)
-   Upgrade to Spring Kafka 3.0.9 [#&#8203;36187](https://togithub.com/spring-projects/spring-boot/issues/36187)
-   Upgrade to Spring Security 6.1.2 [#&#8203;36298](https://togithub.com/spring-projects/spring-boot/issues/36298)
-   Upgrade to Tomcat 10.1.11 [#&#8203;36342](https://togithub.com/spring-projects/spring-boot/issues/36342)

#### :heart: Contributors

Thank you to all the contributors who worked on this release:

[@&#8203;Pengfei-Lu](https://togithub.com/Pengfei-Lu), [@&#8203;ThomazPassarelli](https://togithub.com/ThomazPassarelli), [@&#8203;bbulgarelli](https://togithub.com/bbulgarelli), [@&#8203;bedla](https://togithub.com/bedla), [@&#8203;dependabot](https://togithub.com/dependabot)\[bot], [@&#8203;dkswnkk](https://togithub.com/dkswnkk), [@&#8203;dreis2211](https://togithub.com/dreis2211), [@&#8203;eddumelendez](https://togithub.com/eddumelendez), [@&#8203;eydunn](https://togithub.com/eydunn), [@&#8203;garyrussell](https://togithub.com/garyrussell), [@&#8203;izeye](https://togithub.com/izeye), [@&#8203;johnnywiller](https://togithub.com/johnnywiller), [@&#8203;jonatan-ivanov](https://togithub.com/jonatan-ivanov), [@&#8203;jstansel](https://togithub.com/jstansel), [@&#8203;lasselindqvist](https://togithub.com/lasselindqvist), [@&#8203;lmartelli](https://togithub.com/lmartelli), and [@&#8203;quaff](https://togithub.com/quaff)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Never, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these updates again.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Mend Renovate](https://www.mend.io/free-developer-tools/renovate/). View repository job log [here](https://developer.mend.io/github/GoogleCloudPlatform/java-docs-samples).
<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNi4xMS4wIiwidXBkYXRlZEluVmVyIjoiMzYuMTEuMCIsInRhcmdldEJyYW5jaCI6Im1haW4ifQ==-->