chore: refactor dependencies inclusion
modify POM to include beam SDK dependencies via BOM
instead of including them one by one. this approach should
eliminate potential version conflicts that may lead to errors like:
java.lang.NoClassDefFoundError