Fix LinkageError caused by different HttpTransport
java.lang.LinkageError: loader constraint violation: loader 'app' wants to load abstract class com.google.api.client.http.HttpTransport. A different abstract class with the same name was previously loaded by org.eclipse.jetty.webapp.WebAppClassLoader.